[package]
name = "boatbomber/loginsystem"
description = "A simple system for creating and using logins in a Roblox game"
version = "0.1.0"
license = "MIT"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "server"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]

[dependencies]
hashlib = "boatbomber/hashlib@1.0.0"
